package com.direitodescomplicado.web.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ConsumidorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsumidorAllPropertiesEquals(Consumidor expected, Consumidor actual) {
        assertConsumidorAutoGeneratedPropertiesEquals(expected, actual);
        assertConsumidorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsumidorAllUpdatablePropertiesEquals(Consumidor expected, Consumidor actual) {
        assertConsumidorUpdatableFieldsEquals(expected, actual);
        assertConsumidorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsumidorAutoGeneratedPropertiesEquals(Consumidor expected, Consumidor actual) {
        assertThat(actual)
            .as("Verify Consumidor auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsumidorUpdatableFieldsEquals(Consumidor expected, Consumidor actual) {
        // empty method

    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsumidorUpdatableRelationshipsEquals(Consumidor expected, Consumidor actual) {
        // empty method
    }
}
