package com.direitodescomplicado.web.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TrabalhoCLTAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrabalhoCLTAllPropertiesEquals(TrabalhoCLT expected, TrabalhoCLT actual) {
        assertTrabalhoCLTAutoGeneratedPropertiesEquals(expected, actual);
        assertTrabalhoCLTAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrabalhoCLTAllUpdatablePropertiesEquals(TrabalhoCLT expected, TrabalhoCLT actual) {
        assertTrabalhoCLTUpdatableFieldsEquals(expected, actual);
        assertTrabalhoCLTUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrabalhoCLTAutoGeneratedPropertiesEquals(TrabalhoCLT expected, TrabalhoCLT actual) {
        assertThat(actual)
            .as("Verify TrabalhoCLT auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrabalhoCLTUpdatableFieldsEquals(TrabalhoCLT expected, TrabalhoCLT actual) {
        // empty method

    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrabalhoCLTUpdatableRelationshipsEquals(TrabalhoCLT expected, TrabalhoCLT actual) {
        // empty method
    }
}
